#!/usr/bin/env python3

import yaml
import os
from subprocess import run, PIPE
import shutil


def controllers():
    out = run('juju controllers --format yaml',
              shell=True, stderr=PIPE, stdout=PIPE)
    out_yaml = yaml.load(out.stdout.decode())
    return out_yaml['controllers'].keys()


if __name__ == "__main__":
    for controller in controllers():
        print("Destroying: {}".format(controller))
        run('juju kill-controller -y {}'.format(controller), shell=True)

    juju_dir = os.path.join(os.getenv('HOME'), '.local/share/juju')
    shutil.rmtree(juju_dir)
