#!/bin/bash

set -eu
export PATH=/snap/bin:$PATH

TMPDIR=$(mktemp -d)

SPELLDIR=$TMPDIR/spells
SDKDIR=$SPELLDIR/sdk

git clone --depth 1 -q https://github.com/conjure-up/spells $SPELLDIR

. $SDKDIR/common.sh

: ${CHANNEL:=edge}

testLog "Checking latest conjure-up from $CHANNEL release"
if ! snap info conjure-up|grep -q "installed"; then
    sudo snap install conjure-up --classic --$CHANNEL > /dev/null 2>&1 || true
else
    sudo snap refresh conjure-up --classic --$CHANNEL > /dev/null 2>&1 || true
fi

export JUJU_MODEL=conjure-up-test
export JUJU_CONTROLLER=conjure-up-controller

# TODO: provide array of clouds to test against
export CLOUD=localhost

spells=(kubernetes-core \
            canonical-kubernetes \
            openstack-novalxd \
            hadoop-kafka \
            hadoop-processing \
            hadoop-spark \
            realtime-syslog-analytics \
            spark-processing \
            ghost)

for spell in ${spells[@]}; do
    testLog "Deploying $TMPDIR/$spell"
    $SPELLDIR/$spell/tests/deploy --spells-dir $SPELLDIR
    if [ -f $SPELLDIR/$spell/tests/verify ]; then
        testLog "Verifying $spell"
        $SPELLDIR/$spell/tests/verify
    fi
    conjure-down $JUJU_CONTROLLER $JUJU_MODEL
done

juju kill-controller -y $JUJU_CONTROLLER
