#!/bin/bash

set -eux

. vars

git clone https://github.com/conjure-up/conjure-up $CONJUREUP_BASEDIR || true

sudo add-apt-repository -y ppa:jonathonf/python-3.6
sudo apt-get update -q
sudo apt-get remove -qy lxd lxd-client
sudo apt-get -y install jq bsdtar python3.6-dev make snapd libsodium-dev python3-pip
sudo -H pip3 install tox
sudo snap install juju --classic || sudo snap refresh juju
sudo snap refresh lxd
sudo snap install juju-wait --classic
sudo addgroup lxd || true
sudo usermod -a -G lxd "$USER" || true
sudo ln -s /snap/bin/lxc /usr/bin/lxc || true
sudo ln -s /snap/bin/juju /usr/bin/juju || true
sudo bash -c 'for i in 5 10 15 30; do [[ -e /var/snap/lxd/common/lxd/unix.socket ]] && break; sleep $i; done'
sudo -E su "$USER" -c "/snap/bin/lxd init --auto"
sudo -E su "$USER" -c "/snap/bin/lxc network set lxdbr1 ipv6.address none || true"

cd "$CONJUREUP_BASEDIR" && tox -e py35,flake,isort
cd "$CONJUREUP_BASEDIR" && tox -e conjure-dev
