#!/bin/bash

set -eu

# Override cloud to test
: "${CLOUD:=localhost}"

# Snap channel
: "${CHANNEL:=edge}"

export PATH=/snap/bin:$PATH
export CLOUD=$CLOUD
export DEBIAN_FRONTEND=noninteractive
export CONJUREUP_REGISTRY_BRANCH=master

sudo -E apt-get -qq update
sudo -E apt-get install -qyf -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold git python3-yaml make|| true
sudo -E apt-get -qyf -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold dist-upgrade

make travis-sysdeps

sudo addgroup lxd || true
sudo usermod -a -G lxd $USER || true
sudo ln -s /snap/bin/juju /usr/bin/juju
sudo ln -s /usr/bin/lxc /usr/bin/conjure-up.lxc
sudo ln -s /usr/bin/lxd /usr/bin/conjure-up.lxd
sudo service lxd start || true
sudo service redis-server start || true

git clone -q https://github.com/conjure-up/conjure-up && cd conjure-up

tox -e py35,flake,isort
tox -e conjure-dev

spells=(canonical-kubernetes \
        kubernetes-core \
        openstack-novalxd \
        hadoop-kafka \
        hadoop-processing \
        hadoop-spark \
        realtime-syslog-analytics \
        spark-processing \
        ghost
       )

testLog "Running spell tests"
for spell in "${spells[@]}"; do
    sudo -E su $USER -c "source conjure-up/conjure-dev/bin/activate && conjure-up -d --notrack --noreport $spell $CLOUD test-controller test-model"
    juju destroy-model -y test-model
done
exit 0
