#!/bin/bash

set -eux

# Override cloud to test
: "${CLOUD:=localhost}"

# Snap channel
: "${CHANNEL:=edge}"

export PATH=/snap/bin:$PATH
export CLOUD=$CLOUD
export DEBIAN_FRONTEND=noninteractive
export CONJUREUP_REGISTRY_BRANCH=master
export CONJUREUP_BASEDIR=/home/ubuntu/conjure-up
export CONJUREUP_TESTDIR=/home/ubuntu/conjure-up-tests

# annotate each output line with timestamp
annotate() {
    set -o pipefail
    eval "$*" 2>&1 | awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }'
}

function run {
    # cd "$CONJUREUP_BASEDIR" && tox -e py35,flake,isort
    # cd "$CONJUREUP_BASEDIR" && tox -e conjure-dev

    local spells=(kubernetes \
                      openstack
                 )

    echo "Running spell tests"
    for spell in "${spells[@]}"; do
        sudo -E su "$USER" -c "source $CONJUREUP_BASEDIR/conjure-dev/bin/activate && conjure-up -c $CONJUREUP_TESTDIR/deployments/Conjurefile.base -c $CONJUREUP_TESTDIR/deployments/Conjurefile.$CLOUD.$spell" || cat ~/.cache/conjure-up/conjure-up.log && cat ~/.cache/conjure-up/canonical-kubernetes/*.err && cat ~/.cache/conjure-up/canonical-kubernetes/steps/*/*.err
        juju destroy-model -y conjure-tester-model
    done
}

git clone https://github.com/conjure-up/conjure-up $CONJUREUP_BASEDIR
sudo add-apt-repository -y ppa:jonathonf/python-3.6
sudo apt-get update -q
sudo apt-get remove -qy lxd lxd-client
sudo apt-get -y install jq bsdtar python3.6-dev make snapd libsodium-dev python3-pip
sudo -H pip3 install tox
sudo snap install juju --classic || sudo snap refresh juju
sudo snap refresh lxd
sudo snap install juju-wait --classic
sudo addgroup lxd || true
sudo usermod -a -G lxd "$USER" || true
sudo ln -s /snap/bin/lxc /usr/bin/lxc || true
sudo ln -s /snap/bin/juju /usr/bin/juju || true
sudo bash -c 'for i in 5 10 15 30; do [[ -e /var/snap/lxd/common/lxd/unix.socket ]] && break; sleep $i; done'

sudo -E su "$USER" -c "lxd init --auto"
sudo -E su "$USER" -c "lxc network create lxdbr0 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false"
sudo -E su "$USER" -c "lxc profile show default"

annotate run
juju kill-controller -y conjure-tester
