#!/bin/bash

set -ex

# Juju controller to use
: "${CI_CONTROLLER:=jenkins-ci-aws}"

# Juju model to use
: "${CI_MODEL:=conjure-up-tester}"

# Snap channel
: "${CI_SNAP_CHANNEL:=edge}"

# Series
: "${CI_SERIES:=xenial}"

juju switch "$CI_CONTROLLER"
juju destroy-model "$CI_CONTROLLER":"$CI_MODEL" -y --destroy-storage || true
juju add-model -c "$CI_CONTROLLER" "$CI_MODEL"
juju switch "$CI_CONTROLLER":"$CI_MODEL"
juju deploy -m "$CI_CONTROLLER":"$CI_MODEL" ubuntu --constraints "mem=32G root-disk=100G cores=16" --series "$CI_SERIES"
juju-wait -e "$CI_CONTROLLER":"$CI_MODEL" -w

tmpfile=$(mktemp)
cat <<EOF> "$tmpfile"
#sudo add-apt-repository -y ppa:jonathonf/python-3.6
#sudo apt-get update -q
#sudo apt-get -y install jq bsdtar python3.6-dev make snapd libsodium-dev python3-pip git
#sudo -H pip3 install tox
sudo apt-get remove -qy lxd lxd-client
sudo snap install juju --classic || sudo snap refresh juju
sudo snap install lxd || sudo snap refresh lxd
sudo snap install juju-wait --classic
sudo addgroup lxd || true
sudo usermod -a -G lxd ubuntu
sudo ln -s /snap/bin/lxc /usr/bin/lxc
sudo ln -s /snap/bin/juju /usr/bin/juju
sudo bash -c "for (( ; ; )); do [[ -e /var/snap/lxd/common/lxd/unix.socket ]] && break; sleep 5; done"
sudo -E su ubuntu -c "/snap/bin/lxd init --auto"
sudo -E su ubuntu -c "/snap/bin/lxc network set lxdbr1 ipv6.address none || true"
sudo -E su ubuntu -c "/snap/bin/lxc network set lxdbr0 ipv6.address none || true"
sudo -E su ubuntu -c "/snap/bin/lxc profile show default && /snap/bin/lxc config show && /snap/bin/lxc network list && /snap/bin/lxc storage list"
sudo snap install conjure-up --classic --$CI_SNAP_CHANNEL
sudo ln -s /snap/bin/conjure-up /usr/bin/conjure-up
EOF

juju scp -m "$CI_CONTROLLER":"$CI_MODEL" "$tmpfile" ubuntu/0:setup
juju ssh -m "$CI_CONTROLLER":"$CI_MODEL" ubuntu/0 "bash -x setup"
